### ISSUE TITLE
Adjust .gitignore to not exclude the InstantPreview.apk and GVRVideoPlayer.unitypackage

### ISSUE THREAD

**Issue by AmigaAbattoir** [vuplex/google-vr-webview-example#1]
You may want to adjust the .gitignore so that it doesn't exclude some of the Google VR SDK by adding at the end:

```
# Keep around for Google VR SDK
!InstantPreview.apk
!GVRVideoPlayer.unitypackage
```

**Comment by BinaryNate** [comment]
Thanks, @AmigaAbattoir . I just updated the .gitignore like you suggested in order to commit those components.
